// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/form": {
            "post": {
                "description": "Принимает конфигурацию проекта от клиента, запрашивает инфраструктурные метрики и возвращает обработанные данные.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "form"
                ],
                "summary": "Обработка формы",
                "parameters": [
                    {
                        "description": "Данные клиентской формы",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FormResponse"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ScoredPlace"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный формат JSON входных данных",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка работы внутреннего микросервиса",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/genpres": {
            "post": {
                "description": "Принимает обработанную конфигурацию проекта от клиента и LLM генерирует презентацию.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "form"
                ],
                "summary": "Генерация презентации",
                "parameters": [
                    {
                        "description": "Данные для генерации презентации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ScoredPlace"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.LLMResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат JSON входных данных",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка работы внутреннего микросервиса или LLM",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/llm": {
            "post": {
                "description": "Принимает обработанную конфигурацию проекта от клиента и генерирует рекомендацию от LLM.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "form"
                ],
                "summary": "Генерация рекомендации",
                "parameters": [
                    {
                        "description": "Данные для генерации рекомендации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ScoredPlace"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.LLMResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат JSON входных данных",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка работы внутреннего микросервиса или LLM",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Возвращает 200 OK, если шлюз запущен и работает.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверка работоспособности",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AreasM2": {
            "type": "object",
            "properties": {
                "housing": {
                    "type": "number"
                },
                "infrastructure_and_roads": {
                    "type": "number"
                },
                "office": {
                    "type": "number"
                },
                "shop": {
                    "type": "number"
                },
                "social_objects": {
                    "type": "number"
                },
                "total_site_area": {
                    "type": "number"
                },
                "warehouse": {
                    "type": "number"
                }
            }
        },
        "models.ColorProfile": {
            "type": "object",
            "properties": {
                "accent": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "primary": {
                    "type": "string"
                },
                "secondary": {
                    "type": "string"
                }
            }
        },
        "models.Coordinates": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        },
        "models.CostsMlnRub": {
            "type": "object",
            "properties": {
                "infrastructure_and_landscaping": {
                    "type": "number"
                },
                "office_and_housing": {
                    "type": "number"
                },
                "power_connection": {
                    "type": "number"
                },
                "production": {
                    "type": "number"
                },
                "social_and_sports": {
                    "type": "number"
                }
            }
        },
        "models.CulturalCode": {
            "type": "object",
            "properties": {
                "color_profile": {
                    "$ref": "#/definitions/models.ColorProfile"
                },
                "dominant_architectural_styles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "traditional_materials_ornaments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.DetailedCostsRub": {
            "type": "object",
            "properties": {
                "АБК (офисный блок)": {
                    "type": "number"
                },
                "Благоустройство территории": {
                    "type": "number"
                },
                "Детский сад": {
                    "type": "number"
                },
                "Дороги и парковки": {
                    "type": "number"
                },
                "Жилье (общежитие/квартиры)": {
                    "type": "number"
                },
                "Медпункт": {
                    "type": "number"
                },
                "Производственный цех": {
                    "type": "number"
                },
                "Склад готовой продукции": {
                    "type": "number"
                },
                "Спортивные объекты": {
                    "type": "number"
                },
                "Столовая": {
                    "type": "number"
                },
                "Технологическое присоединение к сетям": {
                    "type": "number"
                }
            }
        },
        "models.Estimate": {
            "type": "object",
            "properties": {
                "areas_m2": {
                    "$ref": "#/definitions/models.AreasM2"
                },
                "costs_mln_rub": {
                    "$ref": "#/definitions/models.CostsMlnRub"
                },
                "detailed_costs_rub": {
                    "$ref": "#/definitions/models.DetailedCostsRub"
                },
                "insulation_multiplier": {
                    "type": "number"
                },
                "square_m2": {
                    "type": "number"
                },
                "total_mln_rub": {
                    "type": "number"
                }
            }
        },
        "models.Factory": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        },
        "models.FormResponse": {
            "type": "object",
            "properties": {
                "architecturePriority": {
                    "type": "string"
                },
                "budgetMillionRub": {
                    "type": "integer"
                },
                "employeesCount": {
                    "type": "integer"
                },
                "housingPercent": {
                    "type": "integer"
                },
                "housingType": {
                    "type": "string"
                },
                "kindergartenPlacesPer100": {
                    "type": "integer"
                },
                "landscaping": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "maxDistanceToHighwayKm": {
                    "type": "number"
                },
                "productionVolume": {
                    "type": "integer"
                },
                "railwayRequired": {
                    "type": "boolean"
                },
                "sports": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Infrastructure": {
            "type": "object",
            "properties": {
                "available_power_kva": {
                    "type": "number"
                },
                "connection_cost_per_kw": {
                    "type": "number"
                },
                "distance_to_substation_km": {
                    "type": "number"
                },
                "gas_coordinates": {
                    "$ref": "#/definitions/models.Coordinates"
                },
                "has_gas": {
                    "type": "boolean"
                },
                "substation_coordinates": {
                    "$ref": "#/definitions/models.Coordinates"
                }
            }
        },
        "models.Insights": {
            "type": "object",
            "properties": {
                "budget_overrun": {
                    "type": "boolean"
                },
                "budget_overrun_amount": {
                    "type": "number"
                },
                "confidence": {
                    "type": "number"
                },
                "cons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "insulation": {
                    "$ref": "#/definitions/models.Insulation"
                },
                "pros": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "risks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "models.Insulation": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.LLMResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "result": {
                    "type": "string"
                },
                "usage_tokens": {
                    "type": "integer"
                }
            }
        },
        "models.NetworkInfrastructure": {
            "type": "object",
            "properties": {
                "available_electrical_capacity_kva": {
                    "type": "number"
                },
                "technological_connection_fee_rub_kw": {
                    "type": "number"
                }
            }
        },
        "models.Place": {
            "type": "object",
            "properties": {
                "benefit": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "deal_structure": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "distance_to_the_nearest_federal_highway_km": {
                    "type": "number"
                },
                "distance_to_the_nearest_railway_station_km": {
                    "type": "number"
                },
                "estimate": {
                    "$ref": "#/definitions/models.Estimate"
                },
                "id": {
                    "type": "integer"
                },
                "infrastructure": {
                    "$ref": "#/definitions/models.Infrastructure"
                },
                "insights": {
                    "$ref": "#/definitions/models.Insights"
                },
                "min_dist_km_to_insulation_factory": {
                    "type": "number"
                },
                "min_dist_km_to_metallurgical_factory": {
                    "type": "number"
                },
                "nearest_insulation_factory": {
                    "$ref": "#/definitions/models.Factory"
                },
                "nearest_metallurgical_factory": {
                    "$ref": "#/definitions/models.Factory"
                },
                "place_lat": {
                    "type": "number"
                },
                "place_lon": {
                    "type": "number"
                },
                "place_name": {
                    "type": "string"
                },
                "price_rub": {
                    "type": "number"
                },
                "square_ha": {
                    "type": "number"
                },
                "square_m2": {
                    "type": "number"
                }
            }
        },
        "models.RegionEconomy": {
            "type": "object",
            "properties": {
                "average_monthly_salary_rub": {
                    "type": "number"
                },
                "benefits": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ecological_class_iza": {
                    "type": "string"
                },
                "industrial_electricity_tariff_rub_kwh": {
                    "type": "number"
                }
            }
        },
        "models.RegionInfo": {
            "type": "object",
            "properties": {
                "cultural_code": {
                    "$ref": "#/definitions/models.CulturalCode"
                },
                "economy": {
                    "$ref": "#/definitions/models.RegionEconomy"
                },
                "network_infrastructure": {
                    "$ref": "#/definitions/models.NetworkInfrastructure"
                },
                "places": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Place"
                    }
                },
                "region_lat": {
                    "type": "number"
                },
                "region_lon": {
                    "type": "number"
                },
                "region_name": {
                    "type": "string"
                },
                "social_infrastructure": {
                    "$ref": "#/definitions/models.SocialInfrastructure"
                }
            }
        },
        "models.ScoreBreakdown": {
            "type": "object",
            "properties": {
                "economy": {
                    "type": "number"
                },
                "energy": {
                    "type": "number"
                },
                "labor": {
                    "type": "number"
                },
                "logistics": {
                    "type": "number"
                },
                "social": {
                    "type": "number"
                }
            }
        },
        "models.ScoredPlace": {
            "type": "object",
            "properties": {
                "breakdown": {
                    "$ref": "#/definitions/models.ScoreBreakdown"
                },
                "confidence": {
                    "type": "number"
                },
                "place_name": {
                    "type": "string"
                },
                "region_info": {
                    "$ref": "#/definitions/models.RegionInfo"
                },
                "region_name": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "why": {
                    "$ref": "#/definitions/models.WhyInsights"
                }
            }
        },
        "models.SocialInfrastructure": {
            "type": "object",
            "properties": {
                "average_1room_apartment_rent_rub": {
                    "type": "number"
                },
                "kindergarten_availability_per_100_children": {
                    "type": "number"
                },
                "profile_colleges_budget_places": {
                    "type": "number"
                },
                "urban_environment_index": {
                    "type": "number"
                }
            }
        },
        "models.WhyInsights": {
            "type": "object",
            "properties": {
                "cons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pros": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "risks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "top_factor": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gazprom Hackaton Gateway API",
	Description:      "API шлюз для оркестрации запросов к аналитическому и LLM сервисам.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
