// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/form": {
            "post": {
                "description": "Принимает конфигурацию проекта от клиента, запрашивает инфраструктурные метрики и возвращает сгенерированный LLM ответ.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "form"
                ],
                "summary": "Обработка формы и генерация аналитики через LLM",
                "parameters": [
                    {
                        "description": "Данные клиентской формы",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FormResponse"
                        }
                    }
                ],
                "responses": {
                    "211": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.LLMResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат JSON входных данных",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка работы внутренних микросервисов или LLM",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Architecture": {
            "type": "object",
            "properties": {
                "colors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "priority": {
                    "type": "string"
                }
            }
        },
        "models.Constraints": {
            "type": "object",
            "properties": {
                "max_distance_to_highway_km": {
                    "type": "number"
                },
                "max_land_cost": {
                    "type": "number"
                },
                "min_power_capacity": {
                    "type": "number"
                }
            }
        },
        "models.FormResponse": {
            "type": "object",
            "properties": {
                "architecture": {
                    "$ref": "#/definitions/models.Architecture"
                },
                "constraints": {
                    "$ref": "#/definitions/models.Constraints"
                },
                "infrastructure_requirements": {
                    "$ref": "#/definitions/models.InfrastructureRequirements"
                },
                "landscaping": {
                    "$ref": "#/definitions/models.Landscaping"
                },
                "meta": {
                    "$ref": "#/definitions/models.Meta"
                },
                "preferences": {
                    "$ref": "#/definitions/models.Preferences"
                },
                "priorities": {
                    "$ref": "#/definitions/models.Priorities"
                },
                "project": {
                    "$ref": "#/definitions/models.Project"
                },
                "requirements": {
                    "$ref": "#/definitions/models.Requirements"
                }
            }
        },
        "models.InfrastructureRequirements": {
            "type": "object",
            "properties": {
                "gas_required": {
                    "type": "boolean"
                },
                "sewage_required": {
                    "type": "boolean"
                },
                "water_required": {
                    "type": "boolean"
                }
            }
        },
        "models.LLMResponse": {
            "type": "object"
        },
        "models.Landscaping": {
            "type": "object",
            "properties": {
                "selected": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Meta": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.Preferences": {
            "type": "object",
            "properties": {
                "climate": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "region_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Priorities": {
            "type": "object",
            "properties": {
                "economy": {
                    "type": "number"
                },
                "energy": {
                    "type": "number"
                },
                "labor": {
                    "type": "number"
                },
                "logistics": {
                    "type": "number"
                },
                "social": {
                    "type": "number"
                }
            }
        },
        "models.Project": {
            "type": "object",
            "properties": {
                "insulation_type": {
                    "type": "string"
                },
                "production_type": {
                    "type": "string"
                }
            }
        },
        "models.Requirements": {
            "type": "object",
            "properties": {
                "factory_area_m2": {
                    "type": "number"
                },
                "warehouse_area_m2": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3002",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gazprom Hackaton Gateway API",
	Description:      "API шлюз для оркестрации запросов к аналитическому и LLM сервисам.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
