basePath: /
definitions:
  models.Architecture:
    properties:
      colors:
        items:
          type: string
        type: array
      priority:
        type: string
    type: object
  models.Constraints:
    properties:
      max_distance_to_highway_km:
        type: number
      max_land_cost:
        type: number
      min_power_capacity:
        type: number
    type: object
  models.FormResponse:
    properties:
      architecture:
        $ref: '#/definitions/models.Architecture'
      constraints:
        $ref: '#/definitions/models.Constraints'
      infrastructure_requirements:
        $ref: '#/definitions/models.InfrastructureRequirements'
      landscaping:
        $ref: '#/definitions/models.Landscaping'
      meta:
        $ref: '#/definitions/models.Meta'
      preferences:
        $ref: '#/definitions/models.Preferences'
      priorities:
        $ref: '#/definitions/models.Priorities'
      project:
        $ref: '#/definitions/models.Project'
      requirements:
        $ref: '#/definitions/models.Requirements'
    type: object
  models.InfrastructureRequirements:
    properties:
      gas_required:
        type: boolean
      sewage_required:
        type: boolean
      water_required:
        type: boolean
    type: object
  models.LLMResponse:
    type: object
  models.Landscaping:
    properties:
      selected:
        items:
          type: string
        type: array
    type: object
  models.Meta:
    properties:
      request_id:
        type: string
      timestamp:
        type: string
    type: object
  models.Preferences:
    properties:
      climate:
        items:
          type: string
        type: array
      region_types:
        items:
          type: string
        type: array
    type: object
  models.Priorities:
    properties:
      economy:
        type: number
      energy:
        type: number
      labor:
        type: number
      logistics:
        type: number
      social:
        type: number
    type: object
  models.Project:
    properties:
      insulation_type:
        type: string
      production_type:
        type: string
    type: object
  models.Requirements:
    properties:
      factory_area_m2:
        type: number
      warehouse_area_m2:
        type: number
    type: object
host: localhost:3002
info:
  contact: {}
  description: API шлюз для оркестрации запросов к аналитическому и LLM сервисам.
  title: Gazprom Hackaton Gateway API
  version: "1.0"
paths:
  /api/v1/form:
    post:
      consumes:
      - application/json
      description: Принимает конфигурацию проекта от клиента, запрашивает инфраструктурные
        метрики и возвращает сгенерированный LLM ответ.
      parameters:
      - description: Данные клиентской формы
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.FormResponse'
      produces:
      - application/json
      responses:
        "211":
          description: ""
          schema:
            $ref: '#/definitions/models.LLMResponse'
        "400":
          description: Неверный формат JSON входных данных
          schema:
            properties:
              error:
                type: string
              message:
                type: string
            type: object
        "500":
          description: Ошибка работы внутренних микросервисов или LLM
          schema:
            properties:
              error:
                type: string
              message:
                type: string
            type: object
      summary: Обработка формы и генерация аналитики через LLM
      tags:
      - form
swagger: "2.0"
